; 菜单配置文件
; 功能：控制台变量菜单配置
; 用途：配合“Commands Menu”插件，定义可通过菜单修改的控制台变量（cvars）
; 文件位置： $moddir/addons/amxmodx/configs/cvars.ini
; 与命令菜单插件一起使用

; 参数菜单:
; < cvar > < values > ... < access level >
; <cvar> <值1> <值2> ... <访问权限>

"mp_timelimit"		"0" "30" "45"		"u"
"sv_password"		"" "mypw" "clanwar"	"u"
"pausable"		"0" "1"			"u"
"sv_voiceenable"	"0" "1"			"u"
"mp_chattime"		"0" "1" "3"		"u"
"mp_logmessages"	"0" "1"			"u"
"mp_friendlyfire"	"0" "1"			"u"
"mp_limitteams"		"0" "1" "2"		"u"
"mp_autoteambalance"	"0" "1" "2"		"u"
"allow_spectators"	"0" "1"			"u"
"mp_freezetime"		"0" "6"			"u"
"mp_buytime"		"1" "0.5"		"u"
"mp_startmoney"		"800" "1800" "3600"	"u"
"mp_c4timer"		"35" "45" "15"		"u"
"mp_forcechasecam"	"0" "1" "2"		"u"
