; 模块配置文件
; 用途：启用/禁用AMX Mod X模块，移除行首分号（;）即可启用
; 文件位置：$moddir/addons/amxmodx/configs/modules.ini

;;;
; 如果下方不包含要使用的模块，可增加模块名称.
; 无需使用模块文件名称中的_amxx和扩展名.
;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SQL模块通常需要手动启用                           ;;
;; 可同时启用任意数量的模块                          ;;
;; 在sql.cfg中使用amx_sql_type指定默认值             ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;mysql
;sqlite

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 下方指定第三方模块.                                ;;
;; 只需使用模块名称                                   ;;
;; 无需使用_amxx和扩展名.                             ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 这些模块根据需要将被自动检测并加载                  ;;
;; 无需在此处启用                                    ;;
;;  除非遇到问题必须强制加载                          ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;fun
;engine
;fakemeta
;geoip
;sockets
;regex
;nvault
;cstrike
;csx
;hamsandwich
