; AMX Mod X 插件列表
; 用途：定义服务器加载的插件，每行一个插件（.amxx扩展名）
; 文件位置：$moddir/addons/amxmodx/configs/plugins.ini


; Admin 基础插件 - 同时只能使用其中一个
admin.amxx		       ; 管理基础插件(任何与管理相关的功能都需要运行)
;admin_sql.amxx		   ; 管理基础插件 - SQL版本 (启用时需禁用admin.amxx)

; 基础功能插件
admincmd.amxx		     ; 控制台基本管理命令插件
adminhelp.amxx		   ; 控制台命令帮助菜单插件
adminslots.amxx		   ; 预留通道插件
multilingual.amxx	   ; 多语言管理插件

; 菜单插件
menufront.amxx	     ; 管理菜单前端插件
cmdmenu.amxx		     ; 命令菜单插件 (语音, 服务器设置等)
plmenu.amxx		       ; 玩家菜单插件 (踢人,封禁, 客户端命令执行等.)
;telemenu.amxx		   ; 传送菜单插件 (需要 Fun 模块支持!)
mapsmenu.amxx		     ; 地图菜单插件 (投票,换图等)
pluginmenu.amxx		   ; 调用插件相关菜单/参数命令插件

; 聊天 / 信息插件
adminchat.amxx		  ; 控制台发送聊天信息插件
antiflood.amxx		  ; 防聊天刷屏插件
scrollmsg.amxx		  ; 滚动消息插件
imessage.amxx		    ; 提示信息插件
adminvote.amxx		  ; 投票系统插件

; 地图相关插件
nextmap.amxx		    ; 显示地图循环列表中下张地图插件
mapchooser.amxx	    ; 允许投票选择下张地图插件
timeleft.amxx		    ; 显示地图剩余时间插件

; 配置插件
pausecfg.amxx		    ; 暂停/恢复插件
statscfg.amxx		    ; 统计配置管理插件


; 自定义 - 下方添加第三方插件
