; 统计配置文件
; 用途：由“Stats Configuration Plugin”生成，定义统计信息显示选项
; 由统计配置插件自动生成,请勿修改！
; 变量描述

ShowAttackers            ;Show Attackers
ShowVictims              ;Show Victims
ShowStats                ;HUD-stats default
SayRankStats             ;Say /rankstats
SayRank                  ;Say /rank
SayTop15                 ;Say /top15
