; 菜单配置文件
; 用途：配合“Commands Menu”插件使用，定义服务器配置相关的菜单选项
; 文件位置：$moddir/addons/amxmodx/configs/configs.ini
; 与命令菜单插件一起使用

; 注意：默认情况下，所有设置的访问级别都设置为 "u"。
; 但是您可以进行更改，以限制对某些设置的访问。

; 命令菜单：; <描述> <命令> <标志> <访问级别>
; "a" - 从服务器控制台执行
; "b" - 从管理员控制台执行
; "c" - 执行到所有客户端
; "d" - 执行后返回菜单

;"PUBLIC Settings"			"servercfgfile server.cfg;exec server.cfg"	"a"	"u"
;"Clanbase"				"exec clanbase.cfg;servercfgfile \'\'"		"a"	"u"
;"Clanbase Charges Only"		"exec clanbase_co.cfg;servercfgfile \'\'"	"a"	"u"
;"Official CAL Match"			"exec cal.cfg;servercfgfile \'\'"		"a"	"u"
;"ProvingGrounds Server Config"		"exec leagues/pg.cfg;servercfgfile \'\'"	"a"	"u"
;"OGL CS Server Config"			"exec ogl.cfg;servercfgfile \'\'"		"a"	"u"
;"OGL CS FF Server Config"		"exec ogl_ff.cfg;servercfgfile \'\'"		"a"	"u"
;"OGL CS Advanced Server Config"	"exec ogl_adv.cfg;servercfgfile \'\'"		"a"	"u"
