; AMX Mod X 核心配置文件
; 用途：配置AMX Mod X的核心路径、日志模式、数据库超时等参数
; 注意：windows系统下使用CRLF格式保存，linux系统下使用LF格式保存.
amxx_logs       addons/amxmodx/logs
amxx_configsdir addons/amxmodx/configs
amxx_datadir    addons/amxmodx/data
amxx_modules    addons/amxmodx/configs/modules.ini
amxx_plugins    addons/amxmodx/configs/plugins.ini
amxx_pluginsdir addons/amxmodx/plugins
amxx_modulesdir addons/amxmodx/modules
amxx_vault      addons/amxmodx/data/vault.ini
; "csstats" 必须在 "csstats_score" 之前
csstats         addons/amxmodx/data/csstats.dat
csstats_score   addons/amxmodx/data/csstats.amxx

; 日志记录模式
; 0 - 不记录日志
; 1 - 每天一个日志文件
; 2 - 每个地图一个日志文件
; 3 - HL 日志
amxx_logging 1

; MySQL 默认超时时间
mysql_timeout 60

; 二进制日志级别
; 将它们相加以获得所需的级别
; 它们仅适用于二进制日志二进制文件
; 1  - 默认
; 2  - 记录内部字符串的设置和获取
; 4  - 记录内部格式
; 8  - 记录所有本地参数
; 16 - 记录内部函数调用 (仅在调试模式下)
; 32 - 记录行号访问 (仅在调试模式下)
bin_logging 49

; 最大二进制日志大小，以兆字节为单位
max_binlog_size 20

; 插件优化标志 - 将它们相加以获得所需的标志
; 如果降低这些标志，可能会防止在老CPU上崩溃
; 设置为 65536 以禁用优化器，而不是 0！
;-------------
; 1 - 浮点运算
; 2 - 浮点比较
; 4 - 浮点舍入
optimizer 7

; 管理员命令标识管理器
; 0 - 启用.
; 1 - 禁用.
disableflagman 0
