; 音效配置文件
; 用途：定义游戏内事件触发的音效（如首杀、连杀、炸弹安放等）
; 要禁用声音，请用 amxmodmenu（统计设置）或使用命令 amx_statscfgmenu 进行禁用
; 格式：<音效名称> <音效路径>（路径不含sound/和.wav）
; 声音名称的长度不能超过 54 个字符（不包括 sound/ 和 .wav 扩展名）
; 否则插件将不能正常使用声音文件，因为不支持快速下载

FirstBloodSound				misc/firstblood
LastManVsOthersSound		misc/oneandonly
LastManDuelSound			misc/maytheforce
HeadShotKillSoundKiller		misc/headshot
HeadShotKillSoundVictim		fvox/flatline
KnifeKillSound				misc/humiliation
DoubleKillSound				misc/doublekill
RoundCounterSound			misc/prepare
GrenadeKillSound			djeyl/grenade
GrenadeSuicideSound			djeyl/witch
BombPlantedSound			djeyl/c4powa
BombDefusedSound			djeyl/laugh
BombFailedSound				djeyl/witch

; 连杀和多杀声音
MultiKillSound				misc/multikill
UltraKillSound				misc/ultrakill
KillingSpreeSound			misc/killingspree
RampageSound				misc/rampage
UnstopableSound				misc/unstoppable
MonsterKillSound			misc/monsterkill
GodLike						misc/godlike
