; 语音菜单配置文件
; 用途：配合“Commands Menu”插件，定义玩家可触发的语音命令
; 文件位置：$moddir/addons/amxmodx/configs/speech.ini
; 与命令菜单插件一起使用

; 注意：默认情况下，所有设置的访问级别都设置为 "u"。
; 但是您可以进行更改，以限制对某些设置的访问。

; 命令菜单：; <描述> <命令> <标志> <访问级别>
; "a" - 从服务器控制台执行
; "b" - 从管理员控制台执行
; "c" - 执行到所有客户端
; "d" - 执行后返回菜单

"Hello!"			"spk \'vox/hello\'"			"cd"	"u"
"Don't think so"		"spk \'barney/dontguess\'"		"cd"	"u"
"Don't ask me"			"spk \'barney/dontaskme\'"		"cd"	"u"
"Hey! Stop that!"		"spk \'barney/donthurtem\'"		"cd"	"u"
"Yup"				"spk \'barney/yup\'"			"cd"	"u"
"Nope"				"spk \'barney/nope\'"			"cd"	"u"
"Maybe"				"spk \'barney/maybe\'"			"cd"	"u"
"Seeya"				"spk \'barney/seeya\'"			"cd"	"u"
"Man that sounded bad"		"spk \'barney/soundsbad\'"		"cd"	"u"
"Hello and die"			"spk \'vox/hello and die\'"		"cd"	"u"
"Move!"				"spk \'hgrunt/move! _comma yessir!\'"	"cd"	"u"
"You will definitely pay!"	"spk \'hgrunt/c2a2_hg_chat5a\'"		"cd"	"u"
"Laughter"			"spk \'hgrunt/c2a3_hg_laugh\'"		"cd"	"u"
"Silence!"			"spk \'hgrunt/silence!\'"		"cd"	"u"
"You talk too much"		"spk \'barney/youtalkmuch\'"		"cd"	"u"
"You thinkin?"			"spk \'barney/thinking\'"		"cd"	"u"
"Open fire Gordon!"		"spk \'barney/openfire\'"		"cd"	"u"
"Couldnt make a bigger mess"	"spk \'barney/bigmess\'"		"cd"	"u"
"I have a Bad feeling"		"spk \'barney/badfeeling\'"		"cd"	"u"
"Yes sir!"			"spk \'hgrunt/yessir!\'"		"cd"	"u"
"No sir"			"spk \'barney/nosir\'"			"cd"	"u"
