; 用户配置文件
; 用途：定义服务器管理员账户及权限
; 文件位置： $moddir/addons/amxmodx/configs/users.ini

; 以;开头的行是注释行

; 权限标识:
; a - 免疫(无法被踢/封禁/处死/扇耳光,也不受其他命令影响)
; b - 预留通道(可进入预留通道)
; c - 使用 amx_kick 命令
; d - 使用 amx_ban 和 amx_unban 命令(永久和临时封禁)
; e - 使用 amx_slay 和 amx_slap 命令
; f - 使用 amx_map 命令
; g - 使用 amx_cvar 命令(并非所有cvar都可用)
; h - 使用 amx_cfg 命令
; i - 使用 amx_chat 和其他聊天命令
; j - 使用 amx_vote 和其他投票命令
; k - 使用 amx_cvar 命令设置 sv_password 参数
; l - 使用 amx_cvar 命令设置 amx_rcon 和 rcon_password 参数
; m - 自定义等级 A (用于第三方插件)
; n - 自定义等级 B
; o - 自定义等级 C
; p - 自定义等级 D
; q - 自定义等级 E
; r - 自定义等级 F
; s - 自定义等级 G
; t - 自定义等级 H
; u - 调用菜单
; v - 使用 amx_ban 和 amx_unban 命令(仅限临时封禁, 关于 amx_unban, 仅在换图前执行封禁)
; z - 普通玩家(非管理员)

; 账号权限:
; a - 如密码无效，则断开玩家连接
; b - 依靠队标并获取权限
; c - 使用SteamID/WONID获取权限
; d - 使用IP地址获取权限
; e - 不检查密码(仅需 name/ip/steamid)
; k - 名称或标签区分大小写.  如:将其设置为名称 "Ham"进行保护并区分大小写(仅权限 "k")
;     则其他人可以使用"haM", "HAM", "ham"等名称, 但不能使用 "Ham".

; 密码:
; 添加到autoexec.cfg文件中: setinfo _pw "<password>"
; 将 _pw 修改为 amx_password_field 的值

; 管理员帐号格式:
; <name|ip|steamid> <password> <access flags> <account flags>

; 管理员账户格式:
; "STEAM_0:0:123456" "" "abcdefghijklmnopqrstuv" "ce"
; "123.45.67.89" "" "abcdefghijklmnopqrstuv" "de"
; "My Name" "my_password" "abcdefghijklmnopqrstuv" "a"

"loopback" "" "abcdefghijklmnopqrstuv" "de"
